### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by eduardfrigola** [PlaymodesStudio/WarpPi#1]
# Screen Renderer -> add TCP/OSC command
- [x] use Homography
- [x] use FBO
# Image Renderer
- [x] load Filename > fade in ...
- [x] stop > fade out  : load a image with invalid filename
- [x] load foldername > slideshow (fade out > load > fade in) for starting point, see [this](https://github.com/eduardfrigola/Image_Slideshow)
- [x] add TCp/OSC commands (possibly implement the ones from video player

---
- [x] add Art-Net Player that inherits from videoPlayer
- [x] add MyIP to WarpPi debug info -> can use [this](https://github.com/bakercp/ofxNetworkUtils)
# TCP connection, master -> slave
- [ ] When slave is trying to connect, server can't open tcp.
- [x] Master reconection is buggy

---
- [x] Image Renderer & VideoRenderer should not work simultaniously ! If image is rendering -> stop video ... if video is playing ... stop image render ! 
- [x] If TCP Connection is not established, the imageRenderer doesn't show up ? Check what happens when there is no connection at startup ...

**Comment by eduardfrigola** [comment]
When there is no slave, reconnection of server is fine
